services:

  backend:
    image: cppd86/FineAgent:latest
    environment:
      - API_KEY=value                                                     # your nvidia api key
      - MAX_CONCURRENT_RUNS=10
      - LANGSMITH_TRACING=true
      - LANGSMITH_ENDPOINT=https://api.smith.langchain.com
      - LANGSMITH_API_KEY=value                                           # your langsmith project api key
      - LANGSMITH_PROJECT=Multi-Agent-Financial-Analysis-System

    ports:
      - "8000:8000"

  frontend:
    image: cppd86/finagent_frontend:latest
    ports:
      - "8080:8080"
    depends_on:
      - backend