name: Build & Push FinAgents System

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------------------------
      # Docker Setup
      # ---------------------------
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---------------------------
      # Build Frontend Image
      # ---------------------------
      - name: Build finagent frontend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/finagent_frontend:latest frontend

      - name: Push finagent frontend
        run: docker push ${{ secrets.DOCKER_USERNAME }}/finagent_frontend:latest

      # ---------------------------
      # Build Backend Agent Image
      # ---------------------------
      - name: Build FineAgent image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/finesgent:latest Backend

      - name: Push FineAgent
        run: docker push ${{ secrets.DOCKER_USERNAME }}/fineagent:latest